Parse kinematic property in link
gazebosim/sdformat pull request #1390
Opened 2024-04-02 02:08 UTC by iche033

# 🎉 New feature

## Summary

Parses `<kinematic>` SDF element in `<link>` and stores the bool value in Link DOM.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-02 07:58 UTC, ahcorde requested changes

2024-04-02 07:58 UTC, ahcorde commented on include/sdf/Link.hh
> +    /// \param[in] _enable True to make the link kinematic only,
```suggestion
    /// \param[in] _kinematic True to make the link kinematic only,
```

2024-04-02 18:27 UTC, iche033 commented on include/sdf/Link.hh
> +    /// \param[in] _enable True to make the link kinematic only,
fixed. [c086ff1](https://github.com/gazebosim/sdformat/pull/1390/commits/c086ff1196ce746eedae73343c7aaf500daca388)

2024-04-04 17:50 UTC, ahcorde approved these changes

2024-04-04 17:56 UTC, merged