Schema accessor
gazebosim/sdformat pull request #1393
Opened 2024-04-05 00:44 UTC by aagrawal05

# 🎉 New feature

Closes #1376

## Summary
1. I've created a script format_sdf.py which reads from the /sdf/1.11 folder and generates/updates the source for all the relevant classes in the src/ and include/ directories as per the suggested implementation.
2. There were DOM elements navsat.sdf and forcetorque.sdf for which the script does not work and I had to manually edit the script because their naming convention did not match the camel-case conversion (they would need to benav_sat.sdf and force_torque.sdf) This may be undesirable from a code style perspective but may be a breaking change—this is a minor point but I just wanted to point it out.
3. The code builds successfully, I have not thoroughly tested it but it does seem to work.
4. I can add tests for the SchemaFile in all the DOM element tests but I thought it might be overkill because the names are hardcoded in the method anyways. I can add it easily with the script if needed.

## Test it
Tests can be done manually as mentioned by the OP in #1376 in his code example.
I could also add tests in the DOM element unit tests, but that might be overkill because the values are hard-coded.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-10 04:03 UTC, azeey requested changes
Thanks for working on this! I have a few comments that should be easy to address.

Regarding testing, I don't think we should create new tests for this, but one way we can make sure it's working is by using `SchemaFile()` instead of hard coded  file names in `ToElement` functions. Perhaps you can update your script to make that change as well?

2024-08-06 03:58 UTC, azeey commented
@aagrawal05 Looks like there are some style issues and a DCO error. Mind fixing them?

2024-08-15 08:45 UTC, aagrawal05 commented
> @aagrawal05 Looks like there are some style issues and a DCO error. Mind fixing them?

Hey @azeey sure let me take a look. The style issues look fairly straightforward and I'll shortly submit changes to fix this. Please let me know if anything further is to be done in terms of functionality.

2024-08-16 04:40 UTC, aagrawal05 commented
Hey @azeey in attempting to resolve the DCO error through a rebase, it appears that I have accidentally re-committed all the 23 commits from my first changes before the merge to my latest changes... 

I believe it may be a bit complicated for me to proceed accurately to revert this from this point. I feel it might be easier to just close PR and create a new PR on a new branch with a single commit (this also has the added benefit of being merged with the latest changes in sdf14).

With regards to the style I believe the errors should be resolved but I need to test with the linter using the workflow.

Please let me know how to proceed.

2024-12-19 19:56 UTC, azeey commented
@aagrawal05 yes, I think I new PR would be cleaner. It would be ideal if you can target `sdf15` as well.

2025-01-07 22:08 UTC, azeey commented
Hi @aagrawal05, any updates on this PR?

2025-01-07 22:26 UTC, closed without merging

2025-01-07 22:26 UTC, aagrawal05 commented
Hey Azeey sure let me just complete go ahead and open the new PR