Add _state suffix to //state subelements
gazebosim/sdformat pull request #1455
Opened 2024-07-08 06:27 UTC by scpeters

# 🦟 Bug fix

Part of https://github.com/gazebosim/sdformat/issues/632, alternative to https://github.com/gazebosim/sdformat/pull/1377

## Summary

There is some overlap in the names used for elements in the `//world/state` specification and elsewhere, for example the [model_state.sdf](https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/model_state.sdf#L2) file [included in state.sdf](https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/state.sdf#L37) defines an element named [model](https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/model_state.sdf#L2). This has caused challenges with aliasing in XSD (see https://github.com/gazebosim/sdformat/issues/632 and https://github.com/gazebosim/sdformat/pull/643), and it would be simpler if some of these elements had different names, so a `_state` suffix is appended to several subelements of the `//state` element. Additionally, the `//joint_state` definition is moved to its own file and included from `state.sdf` so that a `//state/joint_state` element can specify the state of a `//world/joint`.

I made a similar attempt at renaming these state elements in #1377 trying also to support backwards compatibility with a `1_11.convert` file but only achieving partial functionality. Given that the `//state` element hasn't been used in any version of gz-sim, this pull request opts for a breaking change instead of partial support for backwards compatibility.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [X] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-08-09 18:14 UTC, jennuine requested changes
LGTM, in each of the `*_state.sdf` can we add a little more description on what `state` is? For example, what is `joint_state` vs. normal `joint`. Alternatively, adding a more thorough comment in `state.sdf` would be helpful.

Also, since this is a breaking change, shouldn't we add a method of conversion in https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/1_10.convert ?

2024-08-14 00:26 UTC, scpeters commented
> LGTM, in each of the `*_state.sdf` can we add a little more description on what `state` is? For example, what is `joint_state` vs. normal `joint`. Alternatively, adding a more thorough comment in `state.sdf` would be helpful.

👍 

> Also, since this is a breaking change, shouldn't we add a method of conversion in https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/1_10.convert ?

I tried to add that in https://github.com/gazebosim/sdformat/pull/1377, but it was difficult to handle multiple levels of nested models. My last commit in that PR (https://github.com/gazebosim/sdformat/pull/1377/commits/e9de65940850f7449c68ae7a072f109f535e5807) added a failing test showing what wasn't yet working (see [jenkins job result](https://build.osrfoundation.org/job/sdformat-ci-pr_any-noble-amd64/27/testReport/)). The `//state` elements were used in gazebo-classic log files but haven't been used with gz-sim, and enabling automatic conversion would have required substantial updates to the `sdf::Converter` class, so I'm proposing a breaking change here. I believe @azeey concurred during a weekly meeting

2024-08-14 01:11 UTC, scpeters commented
> > LGTM, in each of the `*_state.sdf` can we add a little more description on what `state` is? For example, what is `joint_state` vs. normal `joint`. Alternatively, adding a more thorough comment in `state.sdf` would be helpful.
> 
> 👍

I've updated the description of state elements in https://github.com/gazebosim/sdformat/pull/1455/commits/cd32f6e8a178860649c62327be661b86b199f117

2024-08-14 01:12 UTC, scpeters commented
while updating state descriptions (see  https://github.com/gazebosim/sdformat/commit/cd32f6e8a178860649c62327be661b86b199f117), I decided to allow joints in `//state/insertions` for consistency with `//state/joint_state` in https://github.com/gazebosim/sdformat/pull/1455/commits/33d66341cfa1f8691c6512906533131d1200f130

2024-08-14 16:46 UTC, azeey commented
> > LGTM, in each of the `*_state.sdf` can we add a little more description on what `state` is? For example, what is `joint_state` vs. normal `joint`. Alternatively, adding a more thorough comment in `state.sdf` would be helpful.
> 
> 👍
> 
> > Also, since this is a breaking change, shouldn't we add a method of conversion in https://github.com/gazebosim/sdformat/blob/sdformat14_14.0.0/sdf/1.11/1_10.convert ?
> 
> I tried to add that in #1377, but it was difficult to handle multiple levels of nested models. My last commit in that PR ([e9de659](https://github.com/gazebosim/sdformat/commit/e9de65940850f7449c68ae7a072f109f535e5807)) added a failing test showing what wasn't yet working (see [jenkins job result](https://build.osrfoundation.org/job/sdformat-ci-pr_any-noble-amd64/27/testReport/)). The `//state` elements were used in gazebo-classic log files but haven't been used with gz-sim, and enabling automatic conversion would have required substantial updates to the `sdf::Converter` class, so I'm proposing a breaking change here. I believe @azeey concurred during a weekly meeting

Yes, like @scpeters said, gz-sim hasn't been using the `//state` element, so not having an automatic conversion is not a blocker.

2024-08-16 00:33 UTC, jennuine approved these changes

2024-08-18 21:11 UTC, merged